site_name: thohnb_blog
theme:
  features:
    - content.tabs.link
  
  name: material
  language: vi
  font:
    text: Inter
  palette:
          
     # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: slate
nav:
  - index.md
plugins:
  - blog:
      blog_dir: . # (1)!
      authors: true
      authors_file: .authors.yml
      archive: false
      post_readtime: false
      post_excerpt: optional
markdown_extensions:
  # For admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
    - stylesheets/extra.css